parser: '@typescript-eslint/parser'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
parserOptions:
  ecmaVersion: 2020
  sourceType: 'module'
  # tsconfigRootDir: __dirname
  project:
    - './tsconfig.json'
    - './tsconfig.node.json'
  extraFileExtensions:
    - '.svelte'
env:
  es6: true
  browser: true
overrides:
  - files:
    - '*.svelte'
    processor: 'svelte3/svelte3'
settings:
  'svelte3/typescript': true
plugins:
  - 'svelte3'
  - '@typescript-eslint/eslint-plugin'
ignorePatterns:
  - 'node_modules'
